name: Assign to project

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  assign_pr_to_project:
    name: Assign pull request to project
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign pull request to project
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ github.event.inputs.github-token }}

  assign_issue_to_project:
    name: Assign issue to project
    if: ${{ github.event_name == 'issue' }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue with `bug` or `enhancement` label to project
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ github.event.inputs.github-token }}
        labeled: bug, enhancement
        label-operator: OR