name: Auto Assign to Project

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue/pull request to project
    steps:
    - uses: monry/actions-get-project-id@v2
    id: get-project-id # requires `id` to refer output values with after steps
    with:
      github-token: ${{ secrets.github-token }}
      project-owner: 'koinos'
      project-number: 6
    - run: |
      echo '${{ steps.get-project-id.outputs.project-id }}'
#    - name: Assign new pull requests
#      uses: monry/actions-add-issue-to-project@v2
#      if: github.event.name == 'pull_request'
#      with:
#        github-token: ${{ secrets.github-token }}
#        project-owner: 'koinos'
#        project-number: 6
#        issue-id: ${{ github.event.pull_request.node_id }}

    - name: Assign issues with `bug` or `enhancement` label to project
      id: add-issue-to-project
      uses: monry/actions-add-issue-to-project@v2
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.issue.labels.*.name, 'enhancement')
      with:
        github-token: ${{ secrets.github-token }}
        project-owner: 'koinos'
        project-number: 6
        issue-id: ${{ github.event.issue.node_id }}
    - run: |
      echo '${{ steps.add-issue-to-project.outputs.added-project-item-id }}'
