name: Auto Assign to Project

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue/pull request to project
    steps:

#    - name: Assign new pull requests
#      uses: actions/add-to-project@v0.4.0
#      if: github.event.name == 'pull_request'
#      with:
#        project-url: https://github.com/orgs/koinos/projects/6
#        github-token: ${{ secrets.github-token }}


    - name: Assign issues with `bug` or `enhancement` label to project
      uses: actions/add-to-project@v0.4.0
      if: github.event.name == 'issue'
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ secrets.github-token }}
        labeled: bug, enhancement
        label-operator: OR
