name: Assign to project

on: [workflow_call]

jobs:
    log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ${{ secrets.GITHUB_TOKEN }}

  assign_issue_to_project:
    name: Assign issue to project
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue with `bug` or `enhancement` label to project
      uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labeled: bug, enhancement
        label-operator: OR

  assign_pr_to_project:
    name: Assign pull request to project
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign pull request to project
      uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ secrets.GITHUB_TOKEN }}
